# Generated by Django 4.2.2 on 2023-06-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="E-mail",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
