# Generated by Django 4.2.2 on 2023-07-03 10:50

from django.db import migrations, models

import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0002_alter_person_e_mail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("request_data", jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
