# Generated by Django 4.2.2 on 2023-07-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0003_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="status_code",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="log",
            name="method",
            field=models.CharField(
                choices=[("GET", "GET"), ("POST", "POST")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="request_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
