# Generated by Django 4.2.2 on 2023-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0004_log_status_code_alter_log_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="environment",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
