# Generated by Django 4.2.2 on 2023-07-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0005_log_environment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="environment",
        ),
        migrations.AddField(
            model_name="log",
            name="user",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
