# Generated by Django 4.2.2 on 2023-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="city_of_birth",
            field=models.CharField(max_length=70, blank=True),
        ),
    ]
