# Generated by Django 4.2.2 on 2023-07-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
